title: Sachin Koli
description: Data Engineer
author:
  name: Sachin Koli
  nickname: 
  twitter: sachinkoli
hostname: kolisachint.github.io # used to determine if google analytics should be triggered
url: https://kolisachint.github.io # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:title/

# stuff for jekyll-seo-tag
social:
  name: Sachin Koli
  links:
    - https://twitter.com/sachinkoli
    - https://github.com/kolisachint
    - https://kolisachint.github.io
    - http://www.linkedin.com/in/kolisachint
    - http://www.last.fm/user/kolisachint
    - https://flickr.com/photos/jimeh/
    - https://keybase.io/jimeh
    - https://facebook.com/kolisachint
    - https://www.messenger.com/t/kolisachint

twitter:
  username: sachinkoli

# main page content - kolisachint@gmail.com
email:
  title: "&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#107;&#111;&#108;&#105;&#115;&#97;&#99;&#104;&#105;&#110;&#116;@&#103;&#109;&#97;&#105;&#108;.&#99;&#111;&#109;"
  href: "&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#107;&#111;&#108;&#105;&#115;&#97;&#99;&#104;&#105;&#110;&#116;@&#103;&#109;&#97;&#105;&#108;.&#99;&#111;&#109;"

links:
  - name: github
    url: https://github.com/kolisachint
    class: fa-github
  - name: blog
    url: https://medium.com/@kolisachint
    class: fa-medium
  - name: twitter
    url: https://twitter.com/sachinkoli
    class: fa-twitter
  - name: linkedin
    url: https://www.linkedin.com/in/kolisachint
    class: fa-linkedin
  - name: messenger
    url: https://www.messenger.com/t/kolisachint
    class: fa-facebook
  - name: cv (pdf)
    id: resume
    type: download
    url: https://github.com/kolisachint/kolisachint.github.io/raw/master/Assets/Sachin_Koli_Resume.pdf
    class: fa-file-text-o

# additional stuff
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
