title: Sachin Koli
description: •	Data Warehouse Specialist with over 10 years’ of experience in Data Warehousing and Business Intelligence. 
author:
  name: Sachin Koli
  nickname: Sachin
  twitter: sachinkoli
hostname: kolisachint.github.io # used to determine if google analytics should be triggered
url: https://kolisachint.github.io # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:title/

# stuff for jekyll-seo-tag
social:
  name: Sachin Koli
  links:
    - https://twitter.com/sachinkoli
    - https://github.com/kolisachint
    - https://kolisachint.github.io
    - http://www.linkedin.com/in/kolisachint
    - http://www.last.fm/user/kolisachint
    - https://flickr.com/photos/jimeh/
    - https://keybase.io/jimeh

twitter:
  username: sachinkoli

# main page content
email:
  title: pbagnpg\100wvzru\056zr
  href: "&#109;&#97;&#105;&#108;&#116;&#111;&#58;%63%6s%6r%74%61%63%74@%6n%69%6q%65%68.%6q%65"

links:
  - name: github
    url: https://github.com/kolisachint
    class: fa-github
  - name: blog
    url: https://medium.com/@kolisachint
    class: fa-medium
  - name: twitter
    url: https://twitter.com/sachinkoli
    class: fa-twitter
  - name: linkedin
    url: https://www.linkedin.com/in/kolisachint
    class: fa-linkedin
  - name: cv (pdf)
    id: resume
    type: download
    url: http://assets.jimeh.me/jim-myhrberg-cv.pdf
    class: fa-file-text-o

# additional stuff
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
